// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9m4GQAYg04osxjBtB3JPyGFOfwVBNXkc',
    appId: '1:558114901286:web:972da2378dd943dadd05e7',
    messagingSenderId: '558114901286',
    projectId: 'chatappflutter-5fc38',
    authDomain: 'chatappflutter-5fc38.firebaseapp.com',
    storageBucket: 'chatappflutter-5fc38.appspot.com',
    measurementId: 'G-F31SH3VYGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPJVtpSVWKF40J1YNrTK38YYzM3AaDIw',
    appId: '1:558114901286:android:9dddba1c4c7dc6a4dd05e7',
    messagingSenderId: '558114901286',
    projectId: 'chatappflutter-5fc38',
    storageBucket: 'chatappflutter-5fc38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-QG6w-jDM9WhVeOzWFzjN56lU22Y_OOw',
    appId: '1:558114901286:ios:4e2879b690b639ebdd05e7',
    messagingSenderId: '558114901286',
    projectId: 'chatappflutter-5fc38',
    storageBucket: 'chatappflutter-5fc38.appspot.com',
    iosClientId: '558114901286-defktjg60jgl61iiattd64eocrc0epo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-QG6w-jDM9WhVeOzWFzjN56lU22Y_OOw',
    appId: '1:558114901286:ios:040f555dd8ae81c3dd05e7',
    messagingSenderId: '558114901286',
    projectId: 'chatappflutter-5fc38',
    storageBucket: 'chatappflutter-5fc38.appspot.com',
    iosClientId: '558114901286-r02q6sbi16qcaodu188sifm47jkn8pnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase.RunnerTests',
  );
}
